name: Build

on:
  workflow_dispatch:
  push:

env:
  PLUGIN_NAME: Tempo

jobs:
  build:
    name: Build (${{matrix.platform}})
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: dotnet build PowerToys-Run-Tempo.sln --configuration Release /p:Platform=${{matrix.platform}} /p:EnableWindowsTargeting=true
      - name: Prepare artifact
        run: |
          Remove-Item -Path Community.PowerToys.Run.Plugin.Tempo\bin\* -Recurse -Include *.xml, *.pdb, PowerToys.*, Wox.*
          Rename-Item -Path Community.PowerToys.Run.Plugin.Tempo\bin\${{matrix.platform}}\Release -NewName $env:PLUGIN_NAME
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PLUGIN_NAME}}-${{matrix.platform}}
          path: "Community.PowerToys.Run.Plugin.Tempo\\bin\\${{matrix.platform}}\\${{env.PLUGIN_NAME}}"