name: Release

on:
  push:
    tags:
      - "*.*.*"

env:
  PLUGIN_NAME: Tempo

jobs:
  publish:
    name: Add artifact to release (${{matrix.platform}})
    runs-on: windows-latest
    permissions:
      contents: write
    concurrency: zip_${{matrix.platform}}
    strategy:
      matrix:
        platform: 
          - x64
          - ARM64
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build PowerToys-Run-Tempo.sln --configuration Release /p:Platform=${{matrix.platform}} /p:EnableWindowsTargeting=true
      - name: Prepare artifact
        run: |
          Remove-Item -Path Community.PowerToys.Run.Plugin.Tempo\bin\* -Recurse -Include *.xml, *.pdb, PowerToys.*, Wox.*
          Rename-Item -Path Community.PowerToys.Run.Plugin.Tempo\bin\${{matrix.platform}}\Release -NewName $env:PLUGIN_NAME
          if (Test-Path -Path "${{env.PLUGIN_NAME}}-${{matrix.platform}}.zip")
          {
             Remove-Item -Path "${{env.PLUGIN_NAME}}-${{matrix.platform}}.zip" 
          }
          Compress-Archive -Path Community.PowerToys.Run.Plugin.Tempo\bin\${{matrix.platform}}\$env:PLUGIN_NAME -DestinationPath "${{env.PLUGIN_NAME}}-${{matrix.platform}}.zip"
      - name: Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          fail_on_unmatched_files: false
          generate_release_notes: true
          files: |
            ${{env.PLUGIN_NAME}}-${{matrix.platform}}.zip
